### ISSUE TITLE
the Generate translation YAML file for  models/attributes no working

### ISSUE THREAD

**Issue by nmenag** [amatsuda/i18n_generators#19]
Return this yaml: 
``` yaml
 es:
  activerecord:
    models:
      area: "-//W3C//DTD HTML 4.01 Transitional//EN"  #g
      audited/adapters/active_record/audit: "-//W3C//DTD HTML 4.01 Transitional//EN"  #g
      city: "-//W3C//DTD HTML 4.01 Transitional//EN"  #g
      companies_company_concept: "-//W3C//DTD HTML 4.01 Transitional//EN"  #g
      companies_institution: "-//W3C//DTD HTML 4.01 Transitional//EN"  #g
      companies_user: "-//W3C//DTD HTML 4.01 Transitional//EN"  #g
      company: "-//W3C//DTD HTML 4.01 Transitional//EN"  #g
      company_concept: "-//W3C//DTD HTML 4.01 Transitional//EN"  #g
      constant: "-//W3C//DTD HTML 4.01 Transitional//EN"  #g
      country: "-//W3C//DTD HTML 4.01 Transitional//EN"  #g
      department: "-//W3C//DTD HTML 4.01 Transitional//EN"  #g
 ```

I have this in the Gemfile file: 

`gem 'i18n_generators', '~> 2.0'``

i am working with `Ruby` in the version `'2.3.0'` and Rails in the version `4.2.5`
