### ISSUE TITLE
link with google is broken - can we disable this ?

### ISSUE THREAD

**Issue by koenhandekyn** [amatsuda/i18n_generators#26]
```
nl:
  activerecord:
    models:
      action_mailbox/inbound_email: "-//W3C//DTD HTML 4.01 Transitional//EN"  #g
      action_text/rich_text: "-//W3C//DTD HTML 4.01 Transitional//EN"  #g
      active_storage/attachment: "-//W3C//DTD HTML 4.01 Transitional//EN"  #g
      active_storage/blob: "-//W3C//DTD HTML 4.01 Transitional//EN"  #g
```
