### ISSUE TITLE
Ru locale

### ISSUE THREAD

**Issue by ka8725** [amatsuda/i18n_generators#8]
`rails g i18n_translation ru` generates not translated fields like this:

```
  admin_user:
    current_sign_in_at: current_sign_in_at  #g
    current_sign_in_ip: current_sign_in_ip  #g
    email: email  #g
    encrypted_password: encrypted_password  #g
    last_sign_in_at: last_sign_in_at  #g
    last_sign_in_ip: last_sign_in_ip  #g
    remember_created_at: remember_created_at  #g
    reset_password_sent_at: reset_password_sent_at  #g
    reset_password_token: reset_password_token  #g
```
